import type { Metadata } from "next";
import { Atkinson_Hyperlegible } from "next/font/google";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";

const instrument_sans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const atkinson = Atkinson_Hyperlegible({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={(instrument_sans.variable, atkinson.variable)}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
